PilasTiendaMVC/Controllers/CompradorController.cs
using PilasTiendaMVC.Pilas.BLL;
using PilasTiendaMVC.Pilas.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TiendaPilasMVC.Controllers;

namespace PilasTiendaMVC.Controllers
{
    public class CompradorController : CacheController
    {
        Negocios neg = new Negocios();  
        // GET: Comprador
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> Listar()
        {
            try
            {
                if (Usuario_AUTH())
                {
                    No_cache(); // Lógica para deshabilitar el caché del controlador de caché
                    List<Pila> listaPilas = await neg.ObtenerProductos();
                    return View(listaPilas);
                }
                else
                {
                    return RedirectToAction("Login", "Login");
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Error al obtener la lista de pilas: " + ex.Message;
                return View();
            }
        }


        public async Task<ActionResult> MostrarCarrito(int id)
        {
            try
            {
                if (Usuario_AUTH())
                {
                    No_cache();
                    Pila producto = await neg.EditarProducto(id);

                    if (producto != null)
                    {
                        return View(producto);
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "El producto no existe.";
                        return View();
                    }
                }
                else
                {
                    return RedirectToAction("Login", "Login");
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Error al obtener el producto para comprar: " + ex.Message;
                return View();
            }
        }
    }
}

PilasTiendaMVC/Views/Comprador/Listar.cshtml
@model List<PilasTiendaMVC.Pilas.Entities.Pila>

@{
    Layout = "~/Views/Shared/comp.cshtml";

}

<h2>Listado de Pilas</h2>

@if (ViewBag.ErrorMessage != null)
{
    <p>@ViewBag.ErrorMessage</p>
}
else
{
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Compras</th>
        </tr>
        @foreach (var pila in Model)
        {
            <tr>
                <td>@pila.PilaId</td>
                <td>@pila.Nombre</td>
                <td>@pila.Precio</td>
                <td>
                    @Html.ActionLink("Agregar carrito", "MostrarCarrito", new { id = pila.PilaId })
                </td>
            </tr>
        }
    </table>
}

PilasTiendaMVC/Views/Comprador/MostrarCarrito.cshtml
@model PilasTiendaMVC.Pilas.Entities.Pila

<h2>Comprar Producto</h2>

@if (ViewBag.ErrorMessage != null)
{
    <p>@ViewBag.ErrorMessage</p>
}
else
{
    using (Html.BeginForm("Comprar", "Comprador", FormMethod.Post))
    {
        @Html.HiddenFor(model => model.PilaId)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre)
            <p>@Model.Nombre</p>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion)
            <p>@Model.Descripcion</p>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha)
            <p>@Model.Fecha</p>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagen)
            <p>@Model.Imagen</p>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stock)
            @Html.TextBoxFor(model => model.Stock, new { @class = "form-control" })
        </div>
        <br>
        @Html.ActionLink("Comprar", "Comprar" , new { Cantidad = Model.Stock })
    }
}